name: Convert FASTA to Tab-delimited

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install biopython

    - name: Convert FASTA to Tab-delimited
      run: |
        for file in *.fasta; do
          python fasta_to_tab.py "$file" "${file%.fasta}.tsv"
        done

    - name: Commit and push TSV files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add *.tsv
        git commit -m "Add converted TSV files"
        git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}